// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnjRlKHZsKoC2SbMQ9hFp9Ka52YREIXU',
    appId: '1:19721287143:web:134a05a051255e0208f942',
    messagingSenderId: '19721287143',
    projectId: 'meet-par',
    authDomain: 'meet-par.firebaseapp.com',
    storageBucket: 'meet-par.appspot.com',
    measurementId: 'G-0P23J6RWEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbq87EfXeqL7AprDLD8M3n9ThX0vR9uM',
    appId: '1:19721287143:android:a5b3ccd9c2b8766208f942',
    messagingSenderId: '19721287143',
    projectId: 'meet-par',
    storageBucket: 'meet-par.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1rV7nFhp_DsuPxlb9gZrIxUzky4ezBw',
    appId: '1:19721287143:ios:26463c4279a7d63c08f942',
    messagingSenderId: '19721287143',
    projectId: 'meet-par',
    storageBucket: 'meet-par.appspot.com',
    iosClientId: '19721287143-iih0fk1vg9vrrdifcp9iru9ki6ddpm4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetPar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1rV7nFhp_DsuPxlb9gZrIxUzky4ezBw',
    appId: '1:19721287143:ios:26463c4279a7d63c08f942',
    messagingSenderId: '19721287143',
    projectId: 'meet-par',
    storageBucket: 'meet-par.appspot.com',
    iosClientId: '19721287143-iih0fk1vg9vrrdifcp9iru9ki6ddpm4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetPar',
  );
}
